_wandb:
    value:
        cli_version: 0.26.0
        e:
            prgzr7cxfpdufucx7scqo9vvkrwnbdk0:
                args:
                    - --config
                    - configs/baseline_b0.yaml
                codePath: scripts/train_llm_baseline_sft.py
                codePathLocal: scripts/train_llm_baseline_sft.py
                cpu_count: 96
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "53687091200"
                        used: "15557390336"
                email: 1349410043@qq.com
                executable: /data/liaozijie/conda/accelerate-fc/bin/python3.11
                git:
                    commit: 0d4303930a9a754618027b807387dcbfc0029e4b
                    remote: git@github.com:fenglinbei/fact-checking.git
                gpu: NVIDIA L20
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-09b29c25-c372-62f4-3098-9734013e93c0
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-9145ca41-4f0b-6f81-9a0b-118cb4596601
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-278f5973-425f-514a-8a2d-db77f55d481b
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-6e7d956e-0a22-7fac-a093-130cc1190f38
                host: cuda12-4-1-cudnn9-code-conda-878a193fe7034b0ab8-69456f56f94l8lx
                memory:
                    total: "214748364800"
                os: Linux-4.18.0-477.10.1.el8_8.x86_64-x86_64-with-glibc2.35
                program: /data/liaozijie/fact-checking/scripts/train_llm_baseline_sft.py
                python: CPython 3.11.15
                root: /data/liaozijie/fact-checking
                startedAt: "2026-04-21T11:13:09.777232Z"
                writerId: prgzr7cxfpdufucx7scqo9vvkrwnbdk0
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
            "3":
                - 2
                - 13
                - 61
            "4": 3.11.15
            "5": 0.26.0
            "6": 5.5.4
            "12": 0.26.0
            "13": linux-x86_64
baseline:
    value:
        context_k: 1
        do_sample: false
        few_shot_k: 16
        few_shot_mmr_lambda: 0.7
        max_new_tokens: 8
        model_name_or_path: /data/models/Qwen2.5-7B-Instruct
        prompt_mode: zero_shot
        retrieval_batch_size: 256
        retrieval_max_length: 256
        retrieval_model: /data/models/bge-base-en-v1.5/
        temperature: 0
        top_k: 5
        use_context: false
data:
    value:
        test_candidates: outputs/liar-raw/stage_a/stage_a_test.jsonl
        train_candidates: outputs/liar-raw/stage_a/stage_a_train.jsonl
        val_candidates: outputs/liar-raw/stage_a/stage_a_val.jsonl
output_dir:
    value: outputs/liar-raw/llm_baseline
sft_train:
    value:
        bf16: true
        dataloader_num_workers: 4
        deepspeed_config: configs/deepspeed_zero2.json
        empty_cache_on_eval: true
        empty_cache_on_save: true
        empty_cache_steps: 1
        eval_steps: 200
        gradient_accumulation_steps: 8
        gradient_checkpointing: true
        learning_rate: 1e-05
        logging_steps: 10
        lr_scheduler_type: cosine
        max_grad_norm: 1
        max_length: 1024
        num_train_epochs: 2
        padding: longest
        per_device_eval_batch_size: 1
        per_device_train_batch_size: 1
        save_steps: 200
        use_flash_attention_2: true
        use_length_bucket: true
        warmup_ratio: 0.03
        weight_decay: 0
wandb:
    value:
        enabled: true
        entity: null
        log_model: false
        project: fact-checking-stage-ab
        run_name: llm_baseline_b0_sft
        watch: false
