"""Stage-A grid search for sensitivity-gated MMR thresholds.

Offline search over (θ_s, θ_r, λ_low, gating_mode, ε) using:

* a cached ``chunk_mmr_val.pkl`` (the artifact already produced by Phase-2 of
  the standard build pipeline);
* the val-set ``build_*.jsonl`` and ``val_predictions.jsonl`` for each λ on
  the grid, generated by re-running build+infer with different
  ``retrieval.mmr_lambda`` while sharing a single SFT checkpoint
  (e.g. the one trained for fixed λ = 0.7).

Outputs:

* ``dev_grid.csv`` — one row per grid cell, sorted by score desc.
* ``dev_grid.json`` — full search payload including baselines and top-K detail.

Run::

    PYTHONPATH=src python scripts/phase6_rl_mmr/search_sensitivity_thresholds.py \\
        --config configs/rl_mmr/sensitivity_search.yaml
"""
from __future__ import annotations

import argparse
import csv
import json
import pickle
from pathlib import Path
from typing import Any

import numpy as np
import yaml

from fact_checking.build.candidates import ChunkMMRSample, compute_hybrid_scores
from fact_checking.data.constants import LABEL2ID
from fact_checking.rl_mmr.sensitivity import (
    GATE_BASE,
    GATE_FLOOR_BLOCKED,
    GATE_LOW,
    GATE_TRIVIAL,
    gating_decision,
    sensitivity_features,
)
from sft.metrics import _compute_classification_metrics


def load_pickle(path: Path) -> Any:
    with path.open("rb") as f:
        return pickle.load(f)


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _index_predictions_by_event(
    build_rows: list[dict[str, Any]],
    pred_rows: list[dict[str, Any]],
) -> dict[str, dict[str, int]]:
    if len(build_rows) != len(pred_rows):
        raise ValueError(
            f"build/predictions length mismatch: {len(build_rows)} vs {len(pred_rows)}. "
            "Did you regenerate predictions for this build artifact?"
        )
    indexed: dict[str, dict[str, int]] = {}
    for build_row, pred_row in zip(build_rows, pred_rows):
        event_id = str(build_row.get("event_id", "")).strip()
        if not event_id:
            continue
        indexed[event_id] = {
            "pred_id": int(pred_row.get("pred_id", -1)),
            "gold_id": int(pred_row.get("gold_id", -1)),
        }
    return indexed


def _load_lambda_runs(
    runs_cfg: list[dict[str, Any]],
) -> dict[float, dict[str, dict[str, int]]]:
    per_lambda: dict[float, dict[str, dict[str, int]]] = {}
    for entry in runs_cfg:
        lam = float(entry["lambda"])
        build_rows = _read_jsonl(Path(entry["build_jsonl"]))
        pred_rows = _read_jsonl(Path(entry["predictions_jsonl"]))
        per_lambda[lam] = _index_predictions_by_event(build_rows, pred_rows)
    return per_lambda


def _gold_ids_from_runs(
    runs: dict[float, dict[str, dict[str, int]]],
) -> dict[str, int]:
    gold: dict[str, int] = {}
    for lam, by_event in runs.items():
        for ev, rec in by_event.items():
            if rec["gold_id"] >= 0:
                gold.setdefault(ev, rec["gold_id"])
    return gold


def _features_for_samples(
    chunk_samples: list[ChunkMMRSample],
    *,
    alpha_dense: float,
    alpha_lexical: float,
    alpha_bm25: float,
    top_k: int,
    lambdas: tuple[float, float, float],
    pool_redundancy_topn: int,
) -> dict[str, dict[str, Any]]:
    feats_by_event: dict[str, dict[str, Any]] = {}
    for sample in chunk_samples:
        scored = compute_hybrid_scores(sample, alpha_dense, alpha_lexical, alpha_bm25)
        n = int(scored["n"])
        if n == 0:
            feats_by_event[str(sample.event_id)] = {
                "_hybrid_scores": np.zeros((0,), dtype=np.float32),
                "n_candidates": 0,
                "S_low": [],
                "S_base": [],
                "S_probe": [],
                "sens_low_base": 0.0,
                "pool_redundancy": 0.0,
                "mean_rel_low": 0.0,
                "mean_rel_base": 0.0,
            }
            continue
        feats = sensitivity_features(
            scored["hybrid_scores"],
            scored["chunk_emb"],
            top_k=top_k,
            lambdas=lambdas,
            pool_redundancy_topn=pool_redundancy_topn,
        )
        feats["_hybrid_scores"] = scored["hybrid_scores"]
        feats_by_event[str(sample.event_id)] = feats
    return feats_by_event


def _score_grid_cell(
    *,
    feats_by_event: dict[str, dict[str, Any]],
    runs: dict[float, dict[str, dict[str, int]]],
    gold_by_event: dict[str, int],
    gating_mode: str,
    theta_s: float,
    theta_r: float,
    lambda_low: float,
    lambda_base: float,
    relevance_floor_kwargs: dict[str, Any],
    min_n_candidates_for_gate: int,
) -> dict[str, Any]:
    pred_ids: list[int] = []
    gold_ids: list[int] = []
    gate_counts: dict[str, int] = {GATE_LOW: 0, GATE_BASE: 0, GATE_FLOOR_BLOCKED: 0, GATE_TRIVIAL: 0}
    chosen_lambdas: list[float] = []
    missing_lookups = 0

    for event_id, gold in gold_by_event.items():
        feats = feats_by_event.get(event_id)
        if feats is None:
            missing_lookups += 1
            continue
        hybrid_scores = feats["_hybrid_scores"]
        chosen, gate, _extras = gating_decision(
            feats,
            hybrid_scores,
            gating_mode=gating_mode,
            theta_s=theta_s,
            theta_r=theta_r,
            lambda_low=lambda_low,
            lambda_base=lambda_base,
            min_n_candidates_for_gate=min_n_candidates_for_gate,
            relevance_floor_kwargs=relevance_floor_kwargs,
        )
        gate_counts[gate] = gate_counts.get(gate, 0) + 1
        chosen_lambdas.append(float(chosen))

        # Lookup prediction at chosen lambda; fall back to nearest available.
        run = runs.get(float(chosen))
        if run is None:
            available = sorted(runs.keys(), key=lambda v: abs(v - chosen))
            run = runs[available[0]] if available else None
        if run is None:
            missing_lookups += 1
            continue
        pred_record = run.get(event_id)
        if pred_record is None:
            missing_lookups += 1
            continue
        pred_ids.append(int(pred_record["pred_id"]))
        gold_ids.append(int(gold))

    if not pred_ids:
        return {
            "accuracy": 0.0,
            "macro_f1": 0.0,
            "num_samples": 0,
            "gate_counts": gate_counts,
            "mean_chosen_lambda": 0.0,
            "missing_lookups": missing_lookups,
        }
    metrics = _compute_classification_metrics(np.asarray(pred_ids, dtype=np.int64), np.asarray(gold_ids, dtype=np.int64))
    return {
        "accuracy": float(metrics["accuracy"]),
        "macro_f1": float(metrics["macro_f1"]),
        "num_samples": len(pred_ids),
        "gate_counts": gate_counts,
        "mean_chosen_lambda": float(np.mean(chosen_lambdas)) if chosen_lambdas else 0.0,
        "missing_lookups": missing_lookups,
    }


def _fixed_baseline(
    runs: dict[float, dict[str, dict[str, int]]],
    gold_by_event: dict[str, int],
    lambda_fixed: float,
) -> dict[str, Any]:
    run = runs.get(float(lambda_fixed))
    if run is None:
        raise KeyError(
            f"fixed_baseline_lambda={lambda_fixed} not found in runs (available: {sorted(runs.keys())})"
        )
    pred_ids: list[int] = []
    gold_ids: list[int] = []
    for event_id, gold in gold_by_event.items():
        rec = run.get(event_id)
        if rec is None:
            continue
        pred_ids.append(int(rec["pred_id"]))
        gold_ids.append(int(gold))
    metrics = _compute_classification_metrics(np.asarray(pred_ids, dtype=np.int64), np.asarray(gold_ids, dtype=np.int64))
    return {
        "lambda": float(lambda_fixed),
        "accuracy": float(metrics["accuracy"]),
        "macro_f1": float(metrics["macro_f1"]),
        "num_samples": len(pred_ids),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Sensitivity-gated MMR threshold search (stage A).")
    parser.add_argument("--config", type=str, required=True, help="YAML search config.")
    parser.add_argument("--output-dir", type=str, default=None, help="Override search.output_dir.")
    args = parser.parse_args()

    with Path(args.config).open("r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    output_dir = Path(args.output_dir or cfg.get("output_dir", "outputs/rl_mmr/sensitivity_search"))
    output_dir.mkdir(parents=True, exist_ok=True)

    chunk_path = Path(cfg["chunk_mmr_path"])
    print(f"[search] loading chunk_mmr cache: {chunk_path}")
    chunk_samples: list[ChunkMMRSample] = load_pickle(chunk_path)
    print(f"[search] num chunk samples: {len(chunk_samples)}")

    build_cfg = cfg["build_cfg"]
    alpha_dense = float(build_cfg.get("alpha_dense", 0.70))
    alpha_lexical = float(build_cfg.get("alpha_lexical", 0.20))
    alpha_bm25 = float(build_cfg.get("alpha_bm25", 0.10))
    top_k = int(build_cfg.get("top_k", 5))

    runs_cfg = cfg["runs"]
    print(f"[search] loading {len(runs_cfg)} per-lambda runs")
    runs = _load_lambda_runs(runs_cfg)
    available_lambdas = sorted(runs.keys())
    print(f"[search] available lambdas: {available_lambdas}")

    gold_by_event = _gold_ids_from_runs(runs)
    print(f"[search] gold-labeled events: {len(gold_by_event)}")

    search_cfg = cfg.get("search", {}) or {}
    theta_s_grid = [float(x) for x in search_cfg.get("theta_s", [0.2, 0.4, 0.6, 0.8])]
    theta_r_grid = [float(x) for x in search_cfg.get("theta_r", [0.3, 0.4, 0.5, 0.6])]
    lambda_low_grid = [float(x) for x in search_cfg.get("lambda_low", [0.2, 0.3, 0.4])]
    gating_modes = list(search_cfg.get("gating_modes", ["basic", "conservative"]))
    epsilons = [float(x) for x in search_cfg.get("epsilons", [0.02, 0.05, 0.10])]
    lambda_base = float(search_cfg.get("lambda_base", 0.7))
    lambda_probe = float(search_cfg.get("lambda_probe", 1.0))
    pool_redundancy_topn = int(search_cfg.get("pool_redundancy_topn", 32))
    min_n_candidates_for_gate = int(search_cfg.get("min_n_candidates_for_gate", 2))
    relevance_floor_mode = str(search_cfg.get("relevance_floor_mode", "mean_delta")).strip().lower()
    p_floor = float(search_cfg.get("p_floor", 0.50))

    metric_cfg = cfg.get("metric", {}) or {}
    w_acc = float(metric_cfg.get("w_acc", 1.0))
    w_f1 = float(metric_cfg.get("w_macro_f1", 0.0))

    fixed_baseline_lambda = float(cfg.get("fixed_baseline_lambda", lambda_base))
    fixed_baseline = _fixed_baseline(runs, gold_by_event, fixed_baseline_lambda)
    print(f"[search] fixed baseline λ={fixed_baseline_lambda}: {fixed_baseline}")

    # Per-lambda fallback report.
    per_lambda_metrics: dict[float, dict[str, Any]] = {}
    for lam in available_lambdas:
        per_lambda_metrics[lam] = _fixed_baseline(runs, gold_by_event, lam)

    # Cache features by (lambda_low, lambda_base, lambda_probe).
    feats_cache: dict[tuple[float, float, float], dict[str, dict[str, Any]]] = {}

    rows: list[dict[str, Any]] = []
    for lambda_low in lambda_low_grid:
        if lambda_low not in runs:
            print(f"[search][warn] λ_low={lambda_low} has no predictions; will fall back to nearest.")
        key = (lambda_low, lambda_base, lambda_probe)
        if key not in feats_cache:
            print(f"[search] computing features for lambdas={key}")
            feats_cache[key] = _features_for_samples(
                chunk_samples,
                alpha_dense=alpha_dense,
                alpha_lexical=alpha_lexical,
                alpha_bm25=alpha_bm25,
                top_k=top_k,
                lambdas=key,
                pool_redundancy_topn=pool_redundancy_topn,
            )
        feats_by_event = feats_cache[key]

        for gating_mode in gating_modes:
            eps_iter = epsilons if gating_mode == "conservative" else [None]
            for theta_s in theta_s_grid:
                for theta_r in theta_r_grid:
                    for eps in eps_iter:
                        relevance_floor_kwargs = {
                            "mode": relevance_floor_mode,
                            "epsilon": float(eps) if eps is not None else 0.05,
                            "p_floor": p_floor,
                        }
                        cell = _score_grid_cell(
                            feats_by_event=feats_by_event,
                            runs=runs,
                            gold_by_event=gold_by_event,
                            gating_mode=gating_mode,
                            theta_s=theta_s,
                            theta_r=theta_r,
                            lambda_low=lambda_low,
                            lambda_base=lambda_base,
                            relevance_floor_kwargs=relevance_floor_kwargs,
                            min_n_candidates_for_gate=min_n_candidates_for_gate,
                        )
                        score = w_acc * cell["accuracy"] + w_f1 * cell["macro_f1"]
                        rows.append(
                            {
                                "gating_mode": gating_mode,
                                "theta_s": theta_s,
                                "theta_r": theta_r,
                                "lambda_low": lambda_low,
                                "lambda_base": lambda_base,
                                "epsilon": float(eps) if eps is not None else None,
                                "accuracy": cell["accuracy"],
                                "macro_f1": cell["macro_f1"],
                                "score": score,
                                "num_samples": cell["num_samples"],
                                "mean_chosen_lambda": cell["mean_chosen_lambda"],
                                "gate_low": cell["gate_counts"].get(GATE_LOW, 0),
                                "gate_base": cell["gate_counts"].get(GATE_BASE, 0),
                                "gate_floor_blocked": cell["gate_counts"].get(GATE_FLOOR_BLOCKED, 0),
                                "gate_trivial": cell["gate_counts"].get(GATE_TRIVIAL, 0),
                                "missing_lookups": cell["missing_lookups"],
                            }
                        )

    rows.sort(key=lambda r: r["score"], reverse=True)

    csv_path = output_dir / "dev_grid.csv"
    fieldnames = list(rows[0].keys()) if rows else [
        "gating_mode", "theta_s", "theta_r", "lambda_low", "lambda_base", "epsilon",
        "accuracy", "macro_f1", "score", "num_samples", "mean_chosen_lambda",
        "gate_low", "gate_base", "gate_floor_blocked", "gate_trivial", "missing_lookups",
    ]
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)
    print(f"[search] wrote {csv_path}")

    top_k_summary = int(cfg.get("top_k_summary", 10))
    summary = {
        "fixed_baseline": fixed_baseline,
        "per_lambda_baseline": {str(k): v for k, v in per_lambda_metrics.items()},
        "search_metric": {"w_acc": w_acc, "w_macro_f1": w_f1},
        "search_grid": {
            "theta_s": theta_s_grid,
            "theta_r": theta_r_grid,
            "lambda_low": lambda_low_grid,
            "lambda_base": lambda_base,
            "lambda_probe": lambda_probe,
            "gating_modes": gating_modes,
            "epsilons": epsilons,
            "pool_redundancy_topn": pool_redundancy_topn,
            "min_n_candidates_for_gate": min_n_candidates_for_gate,
            "relevance_floor_mode": relevance_floor_mode,
            "p_floor": p_floor,
        },
        "num_grid_cells": len(rows),
        "top_cells": rows[:top_k_summary],
    }
    summary_path = output_dir / "dev_grid.json"
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[search] wrote {summary_path}")
    print(f"[search] best cell: {rows[0] if rows else 'EMPTY'}")


if __name__ == "__main__":
    main()
