#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RUN_LIAR_RAW="${RUN_LIAR_RAW:-true}"
export RUN_RAWFC="${RUN_RAWFC:-false}"
export MODE="${MODE:-build}"
export TRACE_PROMPT_STYLE="${TRACE_PROMPT_STYLE:-mrec_min}"
export LIAR_CASE_SUFFIX="${LIAR_CASE_SUFFIX:-__mrec_t1p0_contrast}"
export MREC_SELECTOR_NAME="${MREC_SELECTOR_NAME:-mrec_greedy_transition_v0_1_t1p0_contrast}"
export MREC_TARGET_RESOLVED_RATE="${MREC_TARGET_RESOLVED_RATE:-1.0}"
export MREC_CONTINUE_AFTER_TARGET_FOR_CONTRAST="${MREC_CONTINUE_AFTER_TARGET_FOR_CONTRAST:-true}"
export MREC_MAX_STEPS="${MREC_MAX_STEPS:-10}"
export MREC_TOKEN_BUDGET="${MREC_TOKEN_BUDGET:-0}"
export FORCE_MREC_BUILD="${FORCE_MREC_BUILD:-true}"
export FORCE_MREC_STAGE="${FORCE_MREC_STAGE:-true}"
export FORCE_BUILD="${FORCE_BUILD:-true}"
export RUN_MREC_DIAGNOSTICS="${RUN_MREC_DIAGNOSTICS:-false}"
export SAMPLE_LIMIT="${SAMPLE_LIMIT:-0}"
export STAGE_SAMPLE_LIMIT="${STAGE_SAMPLE_LIMIT:-$SAMPLE_LIMIT}"

printf '[mrec-quick-ablation] RUN_LIAR_RAW=%s RUN_RAWFC=%s MODE=%s TRACE_PROMPT_STYLE=%s CASE_SUFFIX=%s SELECTOR_NAME=%s TARGET_RESOLVED_RATE=%s CONTINUE_AFTER_TARGET_FOR_CONTRAST=%s RUN_MREC_DIAGNOSTICS=%s\n' \
  "$RUN_LIAR_RAW" "$RUN_RAWFC" "$MODE" "$TRACE_PROMPT_STYLE" "$LIAR_CASE_SUFFIX" "$MREC_SELECTOR_NAME" "$MREC_TARGET_RESOLVED_RATE" "$MREC_CONTINUE_AFTER_TARGET_FOR_CONTRAST" "$RUN_MREC_DIAGNOSTICS"

bash "${SCRIPT_DIR}/run_mrec_ministral3_main.sh"
