#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RUN_LIAR_RAW="${RUN_LIAR_RAW:-true}"
export RUN_RAWFC="${RUN_RAWFC:-false}"
export MODE="${MODE:-full}"
export EVAL_SPLITS="${EVAL_SPLITS:-val,test}"
export TRACE_PROMPT_STYLE="${TRACE_PROMPT_STYLE:-mrec_min}"
export LIAR_CASE_SUFFIX="${LIAR_CASE_SUFFIX:-__mrec_contrast_only_min0}"
export MREC_SELECTOR_NAME="${MREC_SELECTOR_NAME:-mrec_greedy_transition_v0_1_contrast_only_min0}"
export MREC_TARGET_RESOLVED_RATE="${MREC_TARGET_RESOLVED_RATE:-0.80}"
export MREC_CONTINUE_AFTER_TARGET_FOR_CONTRAST="${MREC_CONTINUE_AFTER_TARGET_FOR_CONTRAST:-true}"
export MREC_POST_TARGET_FILL_POLICY="${MREC_POST_TARGET_FILL_POLICY:-contrast_only}"
export MREC_MIN_STEPS="${MREC_MIN_STEPS:-0}"
export MREC_CANDIDATE_TOP_N="${MREC_CANDIDATE_TOP_N:-20}"
export MREC_MAX_STEPS="${MREC_MAX_STEPS:-10}"
export MREC_TOKEN_BUDGET="${MREC_TOKEN_BUDGET:-0}"
export PREPARE_MREC_SOURCES="${PREPARE_MREC_SOURCES:-true}"
export FORCE_MREC_BUILD="${FORCE_MREC_BUILD:-false}"
export FORCE_MREC_STAGE="${FORCE_MREC_STAGE:-true}"
export FORCE_BUILD="${FORCE_BUILD:-auto}"
export RUN_MREC_DIAGNOSTICS="${RUN_MREC_DIAGNOSTICS:-false}"
export RUN_LIAR_TAU_EVAL="${RUN_LIAR_TAU_EVAL:-auto}"
export SAMPLE_LIMIT="${SAMPLE_LIMIT:-0}"
export STAGE_SAMPLE_LIMIT="${STAGE_SAMPLE_LIMIT:-$SAMPLE_LIMIT}"

printf '[mrec-final-liar-raw] RUN_LIAR_RAW=%s RUN_RAWFC=%s MODE=%s EVAL_SPLITS=%s TRACE_PROMPT_STYLE=%s CASE_SUFFIX=%s SELECTOR_NAME=%s TARGET_RESOLVED_RATE=%s CONTINUE_AFTER_TARGET_FOR_CONTRAST=%s POST_TARGET_FILL_POLICY=%s MIN_STEPS=%s CANDIDATE_TOP_N=%s FORCE_MREC_BUILD=%s FORCE_BUILD=%s RUN_MREC_DIAGNOSTICS=%s\n' \
  "$RUN_LIAR_RAW" "$RUN_RAWFC" "$MODE" "$EVAL_SPLITS" "$TRACE_PROMPT_STYLE" "$LIAR_CASE_SUFFIX" "$MREC_SELECTOR_NAME" "$MREC_TARGET_RESOLVED_RATE" "$MREC_CONTINUE_AFTER_TARGET_FOR_CONTRAST" "$MREC_POST_TARGET_FILL_POLICY" "$MREC_MIN_STEPS" "$MREC_CANDIDATE_TOP_N" "$FORCE_MREC_BUILD" "$FORCE_BUILD" "$RUN_MREC_DIAGNOSTICS"

bash "${SCRIPT_DIR}/run_mrec_ministral3_main.sh"
