from fact_checking.models.latent_evidence import LatentEvidenceOrdinalModel, LatentEvidenceOutput
from fact_checking.models.ordinal import coral_decode, coral_loss, coral_targets
from fact_checking.models.sparsemax import masked_sparsemax
